-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY') YEAR, TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH, GENDER, COUNT(DISTINCT(A.USER_ID)) USERS
FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER
ORDER BY 1,2,3
