-- SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(ANIMAL_ID) AS COUNT
-- FROM ANIMAL_OUTS
-- GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
-- ORDER BY 1

-- SELECT HOUR, COUNT(A.DATETIME) AS COUNT
-- FROM ANIMAL_OUTS A RIGHT JOIN (SELECT LEVEL AS HOUR FROM DUAL CONNECT BY LEVEL <= 24) B ON TO_CHAR(A.DATETIME, 'HH24') = B.HOUR
-- GROUP BY HOUR
-- ORDER BY 1

-- SELECT LEVEL-1 AS HOUR
-- FROM DUAL
-- CONNECT BY LEVEL <= 24

SELECT HOUR, COUNT(A.DATETIME) COUNT
FROM ANIMAL_OUTS A RIGHT JOIN (SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24) B ON TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) = HOUR
GROUP BY HOUR
ORDER BY 1
